version: '3.7'

services:
  ui:
    build:
      context: './'
      dockerfile: './src/web/ui/Dockerfile'
    image: 'simplyvc/panic_oasis_ui:2.0.0'
    volumes:
      - './config:/opt/panic_oasis/config'
      - './src/web/ui/sessions:/opt/panic_oasis/src/web/ui/sessions'

    ports:
      - '${UI_HOST_PORT}:9000'
    restart: always

  redis:
    image: 'redis'
    ports:
      - "${REDIS_HOST_PORT}:6379"
    restart: always

  mongo:
    image: 'mongo'
    ports:
      - "${MONGO_HOST_PORT}:27017"
    restart: always

  alerter:
    build: .
    image: 'simplyvc/panic_oasis:2.0.0'
    volumes:
      - './config:/opt/panic_oasis/config'
      - './logs:/opt/panic_oasis/logs'
    restart: always